### ISSUE TITLE
Pneumatic helmet settings loop with newer version of NotEnoughKeys

### ISSUE THREAD

**Issue by artubi** [MineMaarten/PneumaticCraft#767] opened 2015-11-17 13:37 UTC
Hi,
there is an issue between Pneumaticract and newer version of Not Enough Keys. What happens is, after putting Pneumatic helmet into armor slot and pressing inventory key (E), its setting will keep reopening. This causes game to be unplayable and Pneumatic helmet to be unusable. Removing Pneumatic helmet from player armor solves the issue.

Tested with:
PneumaticCraft-1.7.10-1.11.19-141-universal
PneumaticCraft-1.7.10-1.12.1-144-universal
NotEnoughKeys-1.7.10-3.0.0b43-universal

Steps to reproduce:
1. put Pneumatic helmet into player armor slot
2. press inventory key
3. Pneumatic helmet setting opened
4. close it, it will automatically open up again

Notes:
- this doesn't happen with NEK b30
- this same exact issue got Tinkers Construct (1.8.7), with newer versions of NEK, its armor menu kept reopening (didn't happen with NEK b30)
- according do NEK guys, NEK API got major update and that TCon was using old API, which caused this issue

**Comment by MineMaarten** [comment] 2015-12-06 19:25
@TheTemportalist so uhm. is this new API supposed to be backwards compatible?:S According to this issue it doesn't appear to be. I haven't changed anything in the support, so do you happen to know what's happening here?

**Comment by TheTemportalist** [comment] 2015-12-06 19:57
Soooo... Backwards compatibility is currently an issue with NEI, in that it doesnt exist. It should, but I dont have the experience or knowledge yet to implement it.
To answer your question, yes the API was updates and yes, you need to implement a change. Its not difficult, it just is a tweak to make things work better.

**Comment by MineMaarten** [comment] 2015-12-06 20:05
Could you help me with some pointers on how to change? As it sounds like you know what the problem is, and I have no clue, and as it's not a crash, there's no log to look at really.

**Comment by TheTemportalist** [comment] 2015-12-06 20:32
I can absolutely help. I will Twitter DM you and we can work from there.

**Comment by Tomhud94** [comment] 2015-12-27 18:40
You guys figured this out yet? Cause I Just equipped the helmet in the FTB Direwolf20 pack and I didn't even press any buttons and the menu popped up straight away and keeps reopening.

**Comment by Krhymez** [comment] 2016-01-10 17:42
Has there been any work on a fix for this?

**Comment by MineMaarten** [comment] 2016-01-10 17:44
Does disabling NEK's support in the PneumaticCraft config stop the crash? If so, there's your temp fix.

**Comment by MineMaarten** [comment] 2016-01-10 20:20
Ok, I've spoken with @TheTemportalist and we've fixed it. Disabling the NEK support in the PC config should work as a temp fix, but I'll release soon.

**Closed** 2016-01-10 21:39 UTC
Labels: bug, Done in next version (issue will close upon release)

**Comment by evanmoore172004** [comment] 2019-07-18 08:33
So how do I disable the nek. I can’t even play my long ran ftb world now
