### ISSUE TITLE
Oil Buckets not compatible with other tank mods

### ISSUE THREAD

**Issue by KJP12** [MineMaarten/PneumaticCraft#785] opened 2015-12-25 01:44 UTC
When playing this with lots of other mods, the oil bucket is very incompatible with tanks and other mods that can drain and fill buckets. Idea is if the bucket is compatible, it wouldn't be a annoy at all with pumps from other mods, and trying to fill a tank with oil. I really think of this as a nasty bug because you can't drain a tank with this mod's oil in it and fill a tank with this oil bucket.

**Comment by MineMaarten** [comment] 2015-12-25 22:43
I can't really do anything with this I'm afraid. Could you give me instructions to reproduce this? Which mods is it incompatible with? How does it fare on a clean world?

**Comment by KJP12** [comment] 2015-12-26 05:14
To reproduce it is if you have another mod installed with a tank, like Extra Utilities Drums, try rightclicking the drum with the oil bucket, or if there is oil in there because of pump, it can't find the bucket for the fluid.

**Comment by MineMaarten** [comment] 2016-01-29 15:41
We had this issue on a 1.8 test server, and I know the cause, it was there in 1.7 too. I'll look at backporting the fix.

**Comment by MineMaarten** [comment] 2016-01-29 16:01
Fixed with https://github.com/MineMaarten/PneumaticCraft/commit/c55b7db8e2e91f492e045966f861eb66efcd92f6 , fix on curse shortly

**Closed by MineMaarten** 2016-01-29 16:01 UTC
Labels: bug

**Comment by KJP12** [comment] 2016-02-08 02:41
I'll see if the fix works soon enough. Those little things needs to be tested for incase.
