### ISSUE TITLE
RotaryCraft Lubricant conflict

### ISSUE THREAD

**Issue by Hiranus** [MineMaarten/PneumaticCraft#633] opened 2015-08-13 14:45 UTC
After updating from 90 to 118 version of your mod i noticed problems with RC lubricant. I cant pick up RC lube - it only picks up your verision of it, which is unusable within RC, and this makes RC unplayable. Could you talk with @ReikaKalseki and solve this issue somehow? It would be nice if your lube and Reika's were interchangeable.

I will also notify Reika about this.

**Comment by ReikaKalseki** [comment] 2015-08-13 18:23
What is the fluid registry name of PnC lubricant? RC's is simply "lubricant", and I was going to change it to "RC lubricant" in the next MC version update (as it is a world-breaking change, voiding all tanks of lubricant (and jet fuel, which is going to be similarly renamed)).

RC lubricant being interchangeable with PnC is a balance problem for RC and possibly PnC as well.

**Comment by Hiranus** [comment] 2015-08-13 20:58
I don't think that it will be balance problem, at least with the current version of PneumaticCraft. It's only used in "Speed Upgrade" from what i've noticed, so no big issue on PC end. And you require middle tier engine to produce it in larger quantities so in terms of "how easy it's to get this stuff" i think that generating lube in early game is harder in RC. In the late game RC eats crazy amounts of lube, so no big issue there.
I've quickly reverted from 118 to 90 version of PC, so I'm not 100% sure about this, but I think that you need oil to generate lubricant in PC, and RC has similar mechanic. so nothing crazy there too.

**Comment by ReikaKalseki** [comment] 2015-08-13 21:38
> I don't think that it will be balance problem, at least with the current version of PneumaticCraft. It's only used in "Speed Upgrade" from what i've noticed, so no big issue on PC end. And you require middle tier engine to produce it in larger quantities so in terms of "how easy it's to get this stuff" i think that generating lube in early game is harder in RC. In the late game RC eats crazy amounts of lube, so no big issue there.

**Comment by Adraxas** [comment] 2015-08-14 02:31
It is a lot further down the tech tree than the RoC lube and it takes about a minute per bucket and a lot of inferstructure

**Comment by ReikaKalseki** [comment] 2015-08-14 04:47
Harder in another mod still means not requiring any RC.

**Comment by MineMaarten** [comment] 2015-08-14 08:45
I respect changing the id, I'm indeed simply using 'lubricant'. For now though I'd guess the issue is that you're 'hardcoding' checking for your bucket item instead of a 'lubricant' container?

**Comment by ReikaKalseki** [comment] 2015-08-14 18:18
That would be correct, since I never wished for interchangeability.

**Comment by MineMaarten** [comment] 2015-08-15 16:04
Ok, just to be clear, in which case I can close this, as I can't do anything about it on my side.

**Closed by MineMaarten** 2015-08-15 16:04 UTC
Labels: bug

**Comment by MJRLegends** [comment] 2015-12-03 00:30
Was this ever fixed as im still getting problems with it????

**Comment by ReikaKalseki** [comment] 2015-12-03 06:41
The answer to that question should be blatantly obvious.

**Comment by MJRLegends** [comment] 2015-12-03 08:13
Well I'm still getting the issue

**Comment by ReikaKalseki** [comment] 2015-12-03 22:17
And?

**Comment by MJRLegends** [comment] 2015-12-07 14:17
Well the only way to fix it is to change the recipe for the speed upgrades in the PneumaticCraft mod to accept both types of buckets, so will have to do that, but its would be nice to have a permanent fix.

**Comment by ReikaKalseki** [comment] 2015-12-07 20:38
My whole point is that you have been asking if it is fixed when neither mod has released updates.
