### ISSUE TITLE
Compression chamber leak after unload chunk

### ISSUE THREAD

**Issue by mainframecn** [MineMaarten/PneumaticCraft#388] opened 2015-01-27 15:57 UTC
After the chunk containing the compression chamber has been unloaded, the compression chamber seem to have a leak. (not visible) You'd have to break&fix the chamber to build up pressure again.

Happens (as far as i can tell) always when playing on servers.

**Comment by pyure** [comment] 2015-02-01 23:59
Confirmed, in fact I was just about to post same, except that the leak is visible to me (if I look into the chamber through a window)

The multiblock is properly formed and works until you leave the area and return (or log out/back in) at which point the leak appears to be coming from the valve where pressure pipes connect to.

**Comment by pyure** [comment] 2015-02-03 14:38
mainframecn, are you playing on a cauldron server by any chance?  Trying to narrow down potential non-pneumaticcraft culprits in case it helps MineMaarten.

**Comment by mainframecn** [comment] 2015-02-03 14:55
Hi Minemaarten,
I'm playing on north-craft with dw20 1.0.3 pack. Hope that helps.

**Comment by MineMaarten** [comment] 2015-02-04 12:04
It's another of those weird bugs... hard to reproduce, hard to find the cause, hard to validate a fix... I've heard of this before, but I never got in a situation where it happened to me... Is the chamber on a chunk boundary?

**Comment by pyure** [comment] 2015-02-04 20:18
That's easily testable and something I should have thought of already.  I'll try it in the next 24 hours and report back.

If it wasn't a server-specific issue, I'd also see if I could replicate it after ripping other mods out one-by-one to rule out mod interactions.

**Comment by pyure** [comment] 2015-02-05 02:35
mainframecn, can you ask the server owner if its a cauldron server?  Cauldron servers simply provide the admin with extra tools.   A common cauldron tool is the ability to "claim" territory with a golden shovel; another is having entities clump together on the ground automatically to conserve resources.

If MineMaarten notices a trend with cauldron servers it may help him identify a specific problem.

**Comment by pyure** [comment] 2015-02-05 02:37
MineMaarten: Just fyi my chamber is already fully located within a single chunk.  

If it helps, you can see through a chamber window that the air intake valve block itself appears to be leaking (displaying leaking-air particles into the chamber)

**Comment by MineMaarten** [comment] 2015-02-06 11:40
And the texture of the pressure chamber itself...? looks like it's formed, or not (no connected textures)?

**Comment by c1ph3r88** [comment] 2015-02-06 22:28
I am experiencing this same issues as well.  If it helps I have the same results:
-Visible leaking inside chamber
-Chamber multiblock still fully formed
-Entire system is within 1 chunk
-Breaking a chamber block and replacing it fixes issues.

**Comment by lightdamned** [comment] 2015-02-08 17:11
confirmed on dns pack (at launcher) same issue, but i got it only one time after placing the interface, the multi-block loaded up but there was a leaking by the chamber valve (hope could help)

**Comment by pyure** [comment] 2015-02-19 14:20
MineMaarten: see c1ph3r88's comment, mine's identical.  You can still access the GUI of the chamber (so you can still see upgrades inside) but the leak persists until you break any block of the structure (at which point upgrades fall out)

c1ph3r88: are you playing on a Cauldron server?  You may also know it as MCPC+.  I'm attempting to identify a pattern.  If you don't know what this is you can ask your server owner.

**Comment by c1ph3r88** [comment] 2015-02-23 23:18
Pyure: Regular Forge modded server jar.  Version 1277 I believe.

**Comment by pyure** [comment] 2015-02-24 14:20
That's a shame, not cauldron related then.  Thanks kindly.

**Comment by Medason** [comment] 2015-02-24 21:36
I am also having this bug, Direwolf20 modpack, Forge version 1.1.1.322 and pneumaticcraft version 1.6.1-62.  Interestingly enough Railcraft 9.4.0.0 has a similar problem with steam boilers, although they are fixed by relogging while this problem isn't.

**Comment by Pere250** [comment] 2015-03-03 04:28
Having the bug as well. PneumaticCraft 1.5.6-59, Forge 10.13.2.1272. no matter the size they will 'leak' air (black smoke inside) a solution that we use is to keep the chambers loaded with a chunk loader.

**Comment by MineMaarten** [comment] 2015-05-18 19:44
Also got this on ForgeCraft 2 now...

**Comment by MineMaarten** [comment] 2015-05-18 20:44
Okay, I know what variable doesn't get loaded properly to reproduce this. I've added a 'hack' to see when this variable doesn't get properly loaded, and reform the pressure chamber when this is the case. This will be in PneumaticCraft 1.7.1.

**Closed** 2015-06-09 17:41 UTC
Labels: bug, Done in next version (issue will close upon release)

**Comment by pyure** [comment] 2015-06-10 18:07
Thanks as always MineMaarten.

**Comment by MineMaarten** [comment] 2015-06-10 18:21
np, too bad it took that long to fix though ;)
