### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by Sir-Chi** [MineMaarten/PneumaticCraft#820] opened 2016-02-15 11:37 UTC
When I load up the game it gets part way through the loading but then seems to crash. Here's the crash report hopefully you can work out what's causing this.

[crash-2016-02-15_11.31.28-client.txt](https://github.com/MineMaarten/PneumaticCraft/files/130583/crash-2016-02-15_11.31.28-client.txt)

**Comment by MineMaarten** [comment] 2016-02-22 15:12
I have absolutely no clue. Stuff would've to be messed up real bad to even recreate this... The only thing I can think of is that the PneumaticCraft jar is tempered and the SemiBlockInitializer class is changed (to an older version perhaps).

It sounds like a really strange inter-mod problem, and because of the high amount of mods you have I really can't reproduce it. I'd suggest trying to reproduce it by first making sure you have a clean jar of PneumaticCraft, seeing if you have the problems still with just PneumaticCraft in the instance, and also by taking mods out of the mod set you had...

I'm really clueless here..

**Comment by Sir-Chi** [comment] 2016-02-22 15:23
Okay thanks, i'll see what I can do. I'll be sure to let you know what i find & if I can fix it :) thanks for the reply anyways.

**Comment by Sir-Chi** [comment] 2016-02-22 16:07
I managed to find the problem - it was with NHAVE's OmniWrench V3. For some reason the Lib & the mod itself are okay but the problem comes when I add the Integration module. It looks like it messes with the PneumaticCraft jar but I can't be sure. 
Here is another crash report but with only with NHAVE's mod.
[crash-2016-02-22_16.01.11-client.txt](https://github.com/MineMaarten/PneumaticCraft/files/140915/crash-2016-02-22_16.01.11-client.txt)

Hope this helps. Thanks again 
  S.C.

**Comment by MineMaarten** [comment] 2016-02-22 16:44
Hmm, I'd suggest telling the author of that mod (with a link to this issue, possibly, so he can see my view/suspicion on the matter), that would be awesome

**Comment by Sir-Chi** [comment] 2016-02-22 16:51
Okay I'll do that. Thanks again :)

**Comment by nhave** [comment] 2016-02-24 14:59
With the V3 of my mod, i seperated the mod into a core and an integration module.
With that i forgot to create an exeption for the dummy classes i had in my build.gradle.
It should be fixed in V1.0.10 of the integration.

**Comment by Sir-Chi** [comment] 2016-02-24 19:54
Yup can confirm it's all fixed. No more problems!
Thanks guys. :)

**Closed** 2016-02-24 21:13 UTC
Labels: bug, more info needed
